name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install server dependencies
        run: |
          npm --prefix server ci

      - name: Install client dependencies and build
        run: |
          npm --prefix client ci
          npm --prefix client run build

      - name: Lint / quick check
        run: |
          echo "CI completed: dependencies installed and client build created"
